// Copyright (c) 2022 Jorge de Jesus Perez Lopez
// 
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

@api = http://localhost:3000/messages

### GET
GET {{api}}

### POST
POST {{api}}
Content-Type: application/json

{
	"user": "koqkeepl",
	"message": "Hello World"
}
